name = "Miladycraft"
version = "1.6.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47162e13745a15993358a579d8b28409c43a968c62d72913175b804dc5012c10"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
