name = "Miladycraft"
version = "1.6.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8da62c3e54712ee77c929164a26c78ce26df9e2ed4632fe085a2863181aba6d2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
